from .unmountedtype import UnmountedType as UnmountedType
from .utils import get_type as get_type
from typing import Any

class Structure(UnmountedType):
    def __init__(self, of_type: Any, *args: Any, **kwargs: Any) -> None: ...
    @property
    def of_type(self) -> Any: ...
    def get_type(self) -> Any: ...

class List(Structure):
    def __eq__(self, other: Any) -> Any: ...

class NonNull(Structure):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
