from .. import deprecated as deprecated
from ..deprecated import warn_deprecation as warn_deprecation
from typing import Any

def test_warn_deprecation(mocker: Any) -> None: ...
def test_deprecated_decorator(mocker: Any) -> Any: ...
def test_deprecated_class(mocker: Any) -> None: ...
def test_deprecated_decorator_text(mocker: Any) -> Any: ...
def test_deprecated_class_text(mocker: Any) -> None: ...
def test_deprecated_other_object(mocker: Any) -> None: ...
