from ..orderedtype import OrderedType as OrderedType

def test_orderedtype() -> None: ...
def test_orderedtype_eq() -> None: ...
def test_orderedtype_hash() -> None: ...
def test_orderedtype_resetcounter() -> None: ...
def test_orderedtype_non_orderabletypes() -> None: ...
