import graphene
from typing import Any, Optional

class Query(graphene.ObjectType):
    some_field: Any = ...
    def resolve_some_field(self, info: Any, from_: Optional[Any] = ...) -> Any: ...

def test_issue() -> None: ...
