import graphene
from typing import Any

class Query(graphene.ObjectType):
    rand: Any = ...

class Success(graphene.ObjectType):
    yeah: Any = ...

class Error(graphene.ObjectType):
    message: Any = ...

class CreatePostResult(graphene.Union):
    class Meta:
        types: Any = ...

class CreatePost(graphene.Mutation):
    class Input:
        text: Any = ...
    result: Any = ...
    def mutate(self, info: Any, text: Any) -> Any: ...

class Mutations(graphene.ObjectType):
    create_post: Any = ...

def test_create_post() -> None: ...
