from ..context import Context as Context
from ..dynamic import Dynamic as Dynamic
from ..field import Field as Field
from ..inputfield import InputField as InputField
from ..inputobjecttype import InputObjectType as InputObjectType
from ..interface import Interface as Interface
from ..objecttype import ObjectType as ObjectType
from ..scalars import Boolean as Boolean, Int as Int, String as String
from ..schema import Schema as Schema
from ..structures import List as List, NonNull as NonNull
from ..union import Union as Union
from typing import Any

def test_query() -> Any: ...
def test_query_source() -> Any: ...
def test_query_union() -> Any: ...
def test_query_interface() -> Any: ...
def test_query_dynamic() -> Any: ...
def test_query_default_value() -> None: ...
def test_query_wrong_default_value() -> Any: ...
def test_query_default_value_ignored_by_resolver() -> Any: ...
def test_query_resolve_function() -> Any: ...
def test_query_arguments() -> Any: ...
def test_query_input_field() -> Any: ...
def test_query_middlewares() -> Any: ...
def test_objecttype_on_instances() -> Any: ...
def test_big_list_query_benchmark(benchmark: Any) -> Any: ...
def test_big_list_query_compiled_query_benchmark(benchmark: Any) -> Any: ...
def test_big_list_of_containers_query_benchmark(benchmark: Any) -> Any: ...
def test_big_list_of_containers_multiple_fields_query_benchmark(benchmark: Any) -> Any: ...
def test_big_list_of_containers_multiple_fields_custom_resolvers_query_benchmark(benchmark: Any) -> Any: ...
def test_query_annotated_resolvers() -> Any: ...
def test_default_as_kwarg_to_NonNull() -> Any: ...
