from ..inputfield import InputField as InputField
from ..structures import NonNull as NonNull
from .utils import MyLazyType as MyLazyType

def test_inputfield_required() -> None: ...
def test_inputfield_with_lazy_type() -> Any: ...
def test_inputfield_with_lazy_partial_type() -> Any: ...
def test_inputfield_with_string_type() -> None: ...
