from ..argument import Argument as Argument
from ..enum import Enum as Enum, PyEnum as PyEnum
from ..field import Field as Field
from ..inputfield import InputField as InputField
from ..schema import ObjectType as ObjectType, Schema as Schema

def test_enum_construction() -> Any: ...
def test_enum_construction_meta() -> None: ...
def test_enum_instance_construction() -> None: ...
def test_enum_from_builtin_enum() -> None: ...
def test_enum_from_builtin_enum_accepts_lambda_description() -> Any: ...
def test_enum_from_python3_enum_uses_enum_doc() -> None: ...
def test_enum_value_from_class() -> None: ...
def test_enum_value_as_unmounted_field() -> None: ...
def test_enum_value_as_unmounted_inputfield() -> None: ...
def test_enum_value_as_unmounted_argument() -> None: ...
def test_enum_can_be_compared() -> None: ...
def test_enum_can_be_initialzied() -> None: ...
def test_enum_can_retrieve_members() -> None: ...
def test_enum_to_enum_comparison_should_differ() -> None: ...
def test_enum_skip_meta_from_members() -> None: ...
