from ..field import Field as Field
from ..interface import Interface as Interface
from ..unmountedtype import UnmountedType as UnmountedType

class MyType: ...

class MyScalar(UnmountedType):
    def get_type(self) -> Any: ...

def test_generate_interface() -> None: ...
def test_generate_interface_with_meta() -> None: ...
def test_generate_interface_with_fields() -> None: ...
def test_ordered_fields_in_interface() -> None: ...
def test_generate_interface_unmountedtype() -> None: ...
def test_generate_interface_inherit_abstracttype() -> None: ...
def test_generate_interface_inherit_interface() -> None: ...
def test_generate_interface_inherit_abstracttype_reversed() -> None: ...
