from ..field import Field as Field
from ..scalars import String as String
from typing import Any

class CustomField(Field):
    metadata: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

def test_mounted_type() -> None: ...
def test_mounted_type_custom() -> None: ...
