from ..decimal import Decimal as Decimal
from ..objecttype import ObjectType as ObjectType
from ..schema import Schema as Schema
from typing import Any

class Query(ObjectType):
    decimal: Any = ...
    def resolve_decimal(self, info: Any, input: Any) -> Any: ...

schema: Any

def test_decimal_string_query() -> None: ...
def test_decimal_string_query_variable() -> None: ...
def test_bad_decimal_query() -> None: ...
