from ..field import Field as Field
from ..objecttype import ObjectType as ObjectType
from ..union import Union as Union
from ..unmountedtype import UnmountedType as UnmountedType

class MyObjectType1(ObjectType): ...
class MyObjectType2(ObjectType): ...

def test_generate_union() -> None: ...
def test_generate_union_with_meta() -> None: ...
def test_generate_union_with_no_types() -> None: ...
def test_union_can_be_mounted() -> None: ...
